### ISSUE TITLE
In model definition: merge states and odes block...

### ISSUE THREAD

**Issue by jvanhoefer** [martamatos/yaml2sbml#5]
I am currently implementing my first medium sized model using yaml2sbml and I noticed, that we currently have the state + ode definition in a rather redundant way. Wouldn't it be more intuitive to have

```yaml

odes:
    - stateId: S
      rightHandSide: k*S
      initialValue: 1
```

instead of having the states defined in one place and the ODE in another (with potential states w.o. right hand side and vice versa...)?

What do you think @martamatos ?

**Comment by jvanhoefer** [comment]
Current format would look like

```yaml

states: 

    - id: S
       initial_value: 1

odes:
    - state: S
       right_hand_side: k*S
```
